### ISSUE TITLE
Implement database authentication

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#327]

**Comment by yuvrxj-afk** [comment]
would you please give a description for the same?

**Comment by mStirner** [comment]
When you want to connect to a secured mongodb, which requires username and password authentication, the only possible solution is to set via environment variable (`DATABASE_URL`) the full url. E.g. `mongodb://<user>:<pass>:27017/OpenHaus`.

I want to implement a option, that only the username and password must be set. E.g.: `DATABASE_USERNAME`, `DATABASE_PASSWORD`.

**Comment by yuvrxj-afk** [comment]
I added though, Lemme know as you check it.
