### ISSUE TITLE
Remove color.js due to corruption

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/backend#63]
See more here: https://github.com/Marak/colors.js/issues/285

More to read/view
https://github.com/Marak/faker.js/commit/2c4f82f0af819e2bdb2623f0e429754f38c2c2f2#diff-1550ec65ac92f65817fc28928dfef526912b5f52356ff43651369bae92f56031

https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/

**Comment by DABH** [comment]
@mStirner This is not necessary now since the compromised versions have been removed from NPM, but if you are concerned, you can just change your package.json's reference from "colors" to "@dabh/colors" and you should be good to go.  Thanks!

**Comment by mStirner** [comment]
Switch to chalk?
